image:
  file: .gitpod.Dockerfile

tasks:
  - name: Drupal start
    init: |
      lando start
      lando composer install
      lando db-import drupal9.2021-07-15-1626351128.sql.gz

vscode:
  extensions:
    - felixfbecker.php-debug
    - dbaeumer.vscode-eslint
    - eamodio.gitlens
    - EditorConfig.EditorConfig
    - esbenp.prettier-vscode
    - stylelint.vscode-stylelint
    - tombonnike.vscode-status-bar-format-toggle
    - usernamehw.errorlens
    - skippednote.vs-code-drupal
    - mhutchie.git-graph
